version: '3.8'

services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: online_course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"